# AUTO-GENERATED by scripts/gen_errors.py — do not edit. Edit contracts/errors/catalog.yaml.
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


@dataclass(frozen=True)
class ErrorEntry:
    code: str
    slug: str
    domain: str
    http_status: int
    severity: str
    classification: str
    confidentiality: str
    retryable: bool
    owner: str
    title: str
    message: str
    message_i18n: str | None
    remediation: str | None
    auto_repair: dict


class ErrorCode(str, Enum):
    C2004_SYS_0000 = 'C2004-SYS-0000'
    C2004_SYS_0001 = 'C2004-SYS-0001'
    C2004_AUTH_0001 = 'C2004-AUTH-0001'
    C2004_AUTH_0002 = 'C2004-AUTH-0002'
    C2004_AUTH_0003 = 'C2004-AUTH-0003'
    C2004_DATA_0001 = 'C2004-DATA-0001'
    C2004_DATA_0002 = 'C2004-DATA-0002'
    C2004_DATA_0003 = 'C2004-DATA-0003'
    C2004_DATA_0004 = 'C2004-DATA-0004'
    C2004_CFG_0001 = 'C2004-CFG-0001'
    C2004_CFG_0002 = 'C2004-CFG-0002'
    C2004_NET_0001 = 'C2004-NET-0001'
    C2004_NET_0002 = 'C2004-NET-0002'
    C2004_NET_0003 = 'C2004-NET-0003'
    C2004_MENU_0001 = 'C2004-MENU-0001'
    C2004_MENU_0002 = 'C2004-MENU-0002'
    C2004_OPS_0001 = 'C2004-OPS-0001'
    C2004_OPS_0002 = 'C2004-OPS-0002'
    C2004_OPS_0003 = 'C2004-OPS-0003'
    C2004_OPS_0004 = 'C2004-OPS-0004'
    C2004_HW_0011 = 'C2004-HW-0011'
    C2004_HW_0012 = 'C2004-HW-0012'
    C2004_HW_0013 = 'C2004-HW-0013'
    C2004_HW_0014 = 'C2004-HW-0014'


CATALOG: dict[str, ErrorEntry] = {
    'C2004-SYS-0000': ErrorEntry(
        code='C2004-SYS-0000', slug='system.unknown', domain='system',
        http_status=500, severity='critical',
        classification='operational', confidentiality='internal',
        retryable=False, owner='owner://domain/system', title='Unexpected system error',
        message='An unexpected error occurred', message_i18n=None,
        remediation='Check structured logs for the correlation id; this is the catch-all for uncoded failures.', auto_repair={'enabled': False, 'risk': 'high'},
    ),
    'C2004-SYS-0001': ErrorEntry(
        code='C2004-SYS-0001', slug='system.database_error', domain='system',
        http_status=500, severity='error',
        classification='operational', confidentiality='internal',
        retryable=False, owner='owner://domain/system', title='Database operation failed',
        message='Database operation failed', message_i18n=None,
        remediation='Verify the target Postgres service is up (c2004-postgres) and the connection URL is correct.', auto_repair={'enabled': False, 'risk': 'high'},
    ),
    'C2004-AUTH-0001': ErrorEntry(
        code='C2004-AUTH-0001', slug='auth.authentication_required', domain='auth',
        http_status=401, severity='warning',
        classification='security', confidentiality='restricted',
        retryable=False, owner='owner://domain/auth', title='Authentication required',
        message='Authentication is required', message_i18n=None,
        remediation='Sign in again and verify that the session or access token is still valid.', auto_repair={'enabled': False, 'risk': 'high'},
    ),
    'C2004-AUTH-0002': ErrorEntry(
        code='C2004-AUTH-0002', slug='auth.permission_denied', domain='auth',
        http_status=403, severity='warning',
        classification='security', confidentiality='restricted',
        retryable=False, owner='owner://domain/auth', title='Permission denied',
        message='Permission denied', message_i18n=None,
        remediation="Verify the user's role and READ/WRITE permission for the requested resource.", auto_repair={'enabled': False, 'risk': 'high'},
    ),
    'C2004-AUTH-0003': ErrorEntry(
        code='C2004-AUTH-0003', slug='auth.login_rate_limited', domain='auth',
        http_status=429, severity='warning',
        classification='security', confidentiality='restricted',
        retryable=True, owner='owner://domain/auth', title='Too many login attempts',
        message='Too many login attempts. Try again later.', message_i18n=None,
        remediation='Wait for the Retry-After interval before trying to sign in again; investigate repeated failures if they were not expected.', auto_repair={'enabled': False, 'risk': 'high'},
    ),
    'C2004-DATA-0001': ErrorEntry(
        code='C2004-DATA-0001', slug='data.not_found', domain='data',
        http_status=404, severity='warning',
        classification='operational', confidentiality='internal',
        retryable=False, owner='owner://domain/data', title='Resource not found',
        message='The requested resource was not found', message_i18n=None,
        remediation='Confirm the id/name exists; it may have been deleted or never created.', auto_repair={'enabled': False, 'risk': 'low'},
    ),
    'C2004-DATA-0002': ErrorEntry(
        code='C2004-DATA-0002', slug='data.invalid_field', domain='data',
        http_status=422, severity='warning',
        classification='operational', confidentiality='internal',
        retryable=False, owner='owner://domain/data', title='Invalid request fields',
        message='One or more fields are invalid', message_i18n=None,
        remediation='Check the request against the schema; see metadata.context for the offending field.', auto_repair={'enabled': False, 'risk': 'low'},
    ),
    'C2004-DATA-0003': ErrorEntry(
        code='C2004-DATA-0003', slug='data.conflict', domain='data',
        http_status=409, severity='warning',
        classification='operational', confidentiality='internal',
        retryable=False, owner='owner://domain/data', title='State conflict',
        message='The requested change conflicts with the current state', message_i18n=None,
        remediation='Refresh the resource, verify uniqueness/version constraints, and retry with current data.', auto_repair={'enabled': False, 'risk': 'medium'},
    ),
    'C2004-DATA-0004': ErrorEntry(
        code='C2004-DATA-0004', slug='data.invalid_request', domain='data',
        http_status=400, severity='warning',
        classification='operational', confidentiality='internal',
        retryable=False, owner='owner://domain/data', title='Invalid request',
        message='The request is invalid', message_i18n=None,
        remediation='Correct the request syntax or unsupported value described in metadata.context and submit it again.', auto_repair={'enabled': False, 'risk': 'low'},
    ),
    'C2004-CFG-0001': ErrorEntry(
        code='C2004-CFG-0001', slug='config.route_render_timeout', domain='config',
        http_status=500, severity='error',
        classification='operational', confidentiality='internal',
        retryable=True, owner='owner://domain/config', title='Configuration route did not render',
        message='The configuration route did not render within the health-check budget', message_i18n=None,
        remediation='Open the route URL, inspect the module container and browser console, then verify its lazy module registration and dependencies.', auto_repair={'enabled': False, 'risk': 'medium'},
    ),
    'C2004-CFG-0002': ErrorEntry(
        code='C2004-CFG-0002', slug='config.route_runtime_error', domain='config',
        http_status=500, severity='error',
        classification='operational', confidentiality='internal',
        retryable=False, owner='owner://domain/config', title='Configuration route reported a runtime error',
        message='The configuration route rendered an explicit module error', message_i18n=None,
        remediation='Open the affected route and use the linked occurrence details to inspect the captured error, route, module and URL.', auto_repair={'enabled': False, 'risk': 'medium'},
    ),
    'C2004-NET-0001': ErrorEntry(
        code='C2004-NET-0001', slug='network.upstream_unreachable', domain='network',
        http_status=502, severity='error',
        classification='operational', confidentiality='internal',
        retryable=True, owner='owner://domain/infrastructure', title='Upstream service unreachable',
        message='An upstream service is unreachable', message_i18n=None,
        remediation='Check the target service health, proxy route, DNS/address and network connectivity.', auto_repair={'enabled': False, 'risk': 'medium'},
    ),
    'C2004-NET-0002': ErrorEntry(
        code='C2004-NET-0002', slug='network.service_unavailable', domain='network',
        http_status=503, severity='error',
        classification='operational', confidentiality='internal',
        retryable=True, owner='owner://domain/infrastructure', title='Service unavailable',
        message='The requested service is unavailable', message_i18n=None,
        remediation='Check service health and startup logs, then retry when the dependency is ready.', auto_repair={'enabled': False, 'risk': 'medium'},
    ),
    'C2004-NET-0003': ErrorEntry(
        code='C2004-NET-0003', slug='network.timeout', domain='network',
        http_status=504, severity='error',
        classification='operational', confidentiality='internal',
        retryable=True, owner='owner://domain/infrastructure', title='Request timeout',
        message='The request timed out', message_i18n=None,
        remediation='Check dependency latency and connectivity; retry only when the operation is idempotent.', auto_repair={'enabled': False, 'risk': 'medium'},
    ),
    'C2004-MENU-0001': ErrorEntry(
        code='C2004-MENU-0001', slug='menu.config_not_found', domain='menu',
        http_status=404, severity='warning',
        classification='operational', confidentiality='internal',
        retryable=False, owner='owner://domain/menu', title='Menu configuration not found',
        message='Menu configuration not found', message_i18n=None,
        remediation="Confirm the configuration name; canonical module menus are '<module>-menu'.", auto_repair={'enabled': False, 'risk': 'low'},
    ),
    'C2004-MENU-0002': ErrorEntry(
        code='C2004-MENU-0002', slug='menu.config_invalid', domain='menu',
        http_status=400, severity='warning',
        classification='operational', confidentiality='internal',
        retryable=False, owner='owner://domain/menu', title='Invalid menu configuration',
        message='Invalid menu configuration request', message_i18n=None,
        remediation='Check the configuration name against GET /api/v3/menu/configurations/allowed-names and the payload schema.', auto_repair={'enabled': False, 'risk': 'low'},
    ),
    'C2004-OPS-0001': ErrorEntry(
        code='C2004-OPS-0001', slug='operations.update.in_progress', domain='operations',
        http_status=409, severity='warning',
        classification='operational', confidentiality='internal',
        retryable=True, owner='owner://domain/infrastructure', title='DisplayNet update in progress',
        message='A DisplayNet deployment or update is currently in progress', message_i18n=None,
        remediation='Wait until deploy_in_progress is false and the update overlay reports completion before retrying operational actions.', auto_repair={'enabled': False, 'risk': 'low'},
    ),
    'C2004-OPS-0002': ErrorEntry(
        code='C2004-OPS-0002', slug='operations.hardware_runtime.fallback', domain='operations',
        http_status=503, severity='warning',
        classification='operational', confidentiality='internal',
        retryable=False, owner='owner://domain/infrastructure', title='Hardware runtime fallback active',
        message='AUTO hardware runtime selection resolved to a local fallback instead of BoardNet', message_i18n=None,
        remediation='Restore the configured BoardNet runtime and verify /api/v3/hardware/proxy-info before running hardware actions.', auto_repair={'enabled': False, 'risk': 'high'},
    ),
    'C2004-OPS-0003': ErrorEntry(
        code='C2004-OPS-0003', slug='operations.update.status_unavailable', domain='operations',
        http_status=503, severity='warning',
        classification='operational', confidentiality='internal',
        retryable=True, owner='owner://domain/infrastructure', title='DisplayNet update status unavailable',
        message='The DisplayNet update status endpoint is unavailable', message_i18n=None,
        remediation='Check /api/v3/update/status and the DisplayNet backend service, then retry.', auto_repair={'enabled': False, 'risk': 'low'},
    ),
    'C2004-OPS-0004': ErrorEntry(
        code='C2004-OPS-0004', slug='operations.deploy.verification_failed', domain='operations',
        http_status=500, severity='error',
        classification='operational', confidentiality='internal',
        retryable=False, owner='owner://domain/infrastructure', title='Deployment verification failed',
        message='A deployment step or its post-deploy verification failed', message_i18n=None,
        remediation='Use the correlation id and deploy step id to inspect the structured deploy event, correct the reported issue, and resume from the failed idempotent step.', auto_repair={'enabled': False, 'risk': 'high'},
    ),
    'C2004-HW-0011': ErrorEntry(
        code='C2004-HW-0011', slug='hardware.oqlos.unreachable', domain='hardware',
        http_status=502, severity='error',
        classification='safety', confidentiality='restricted',
        retryable=False, owner='owner://domain/hardware', title='OqlOS hardware runtime unreachable',
        message='Cannot reach the OqlOS hardware runtime', message_i18n='pressure.firmware-offline',
        remediation='OqlOS on boardnet .122:8202 is down or unreachable; start it and re-check /api/v1/hardware/health.', auto_repair={'enabled': True, 'runbook': 'hardware.restart_oqlos', 'risk': 'medium'},
    ),
    'C2004-HW-0012': ErrorEntry(
        code='C2004-HW-0012', slug='hardware.adc_telemetry.unavailable', domain='hardware',
        http_status=503, severity='error',
        classification='safety', confidentiality='restricted',
        retryable=False, owner='owner://domain/hardware', title='Required hardware unavailable',
        message='A required hardware plugin or sensor path is not available for real operation', message_i18n='pressure.no-communication',
        remediation='Identify the unavailable device from the error (e.g. modbus-io, motor-dri0050, usb-adc-*). For Modbus IO: GET /api/v1/plugins/modbus-io/health, compare the configured port with the USB inventory and /dev/serial/by-id on boardnet .122, then check RS485 power/A-B/GND, baud rate and slave ID. For ADC telemetry: GET /api/v1/hardware/sensors/batch and verify MCP2221A/DFR1184 providers, device paths and permissions.', auto_repair={'enabled': True, 'runbook': 'hardware.restore_adc_telemetry', 'risk': 'medium'},
    ),
    'C2004-HW-0013': ErrorEntry(
        code='C2004-HW-0013', slug='hardware.rs485.port_held', domain='hardware',
        http_status=409, severity='warning',
        classification='safety', confidentiality='restricted',
        retryable=False, owner='owner://domain/hardware', title='RS485 serial port held',
        message='RS485 serial port is held by the OqlOS runtime', message_i18n=None,
        remediation='Release the port (stop OqlOS) before the Modbus wizard probe; see docs/errors/C2004-HW-0013.md.', auto_repair={'enabled': True, 'runbook': 'hardware.release_rs485', 'risk': 'low'},
    ),
    'C2004-HW-0014': ErrorEntry(
        code='C2004-HW-0014', slug='hardware.power.undervoltage', domain='hardware',
        http_status=503, severity='critical',
        classification='safety', confidentiality='restricted',
        retryable=False, owner='owner://domain/hardware', title='BoardNet supply undervoltage',
        message='BoardNet reports active Raspberry Pi supply undervoltage', message_i18n=None,
        remediation='Stop safety-critical hardware operations, use a stable power supply rated for the Raspberry Pi and attached USB devices, then verify that `vcgencmd get_throttled` no longer has bit 0 set. Historical bit 16 alone is a warning, not an active C2004-HW-0014 error.', auto_repair={'enabled': False, 'risk': 'high'},
    ),
}


C2004_CODE_BY_ISSUE: dict[str, str] = {
    'api_diagnostic_command_invalid': 'C2004-DATA-0002',
    'api_invalid_recover_scope': 'C2004-DATA-0002',
    'api_modbus_wizard_invalid_request': 'C2004-DATA-0002',
    'api_oql_transport_disabled': 'C2004-HW-0012',
    'api_systemd_unit_forbidden': 'C2004-AUTH-0002',
    'boardnet_power_condition_active': 'C2004-HW-0014',
    'boardnet_power_condition_historical': 'C2004-HW-0014',
    'boardnet_power_telemetry_unavailable': 'C2004-HW-0012',
    'boardnet_undervoltage_active': 'C2004-HW-0014',
    'config_unavailable': 'C2004-HW-0012',
    'firmware_no_serial_access': 'C2004-HW-0012',
    'firmware_not_real': 'C2004-HW-0012',
    'firmware_unreachable': 'C2004-HW-0011',
    'hw_dri0050_sidecar_unreachable': 'C2004-HW-0012',
    'hw_modbus_no_response': 'C2004-HW-0012',
    'hw_modbus_serial_handle_stale': 'C2004-HW-0012',
    'hw_tic249_sidecar_unreachable': 'C2004-HW-0012',
    'hw_usb_adc_sidecar_unreachable': 'C2004-HW-0012',
    'identify_unavailable': 'C2004-HW-0012',
    'modbus_adapter_only': 'C2004-HW-0012',
    'modbus_adc_adapter_only': 'C2004-HW-0012',
    'modbus_adc_config_mismatch': 'C2004-HW-0012',
    'modbus_adc_config_missing': 'C2004-HW-0012',
    'modbus_adc_disabled_but_present': 'C2004-HW-0012',
    'modbus_adc_not_detected': 'C2004-HW-0012',
    'modbus_config_mismatch': 'C2004-HW-0012',
    'modbus_config_missing': 'C2004-HW-0012',
    'modbus_not_detected': 'C2004-HW-0012',
    'modbus_preflight_exception': 'C2004-HW-0012',
    'pimodbus_unavailable': 'C2004-HW-0012',
    'remote_firmware_no_serial_access': 'C2004-HW-0012',
    'serial_port_busy': 'C2004-HW-0013',
}

C2004_ISSUE_PATTERNS: tuple[tuple[str, str, str], ...] = (
    ('adapter_', '_health_not_ok', 'C2004-HW-0012'),
    ('adapter_', '_not_ok', 'C2004-HW-0012'),
)


def c2004_code_for_issue(issue_code: str) -> str:
    mapped = C2004_CODE_BY_ISSUE.get(issue_code)
    if mapped is not None:
        return mapped
    for prefix, suffix, public_code in C2004_ISSUE_PATTERNS:
        if issue_code.startswith(prefix) and issue_code.endswith(suffix):
            return public_code
    return 'C2004-SYS-0000'
