#!/usr/bin/env python3
"""
Hardware setup and OQL execution script.

This script:
1. Detects available hardware (USB/serial devices)
2. Configures .env with correct hardware settings
3. Loads .env and runs OQL scenarios in execute mode

Usage:
  python setup_hardware_and_run_oql.py <scenario.oql>
  python setup_hardware_and_run_oql.py <scenario.oql> --dry-run
"""

import os
import sys
import argparse
from pathlib import Path
from typing import Optional

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))

try:
    import serial.tools.list_ports
    HAS_SERIAL = True
except ImportError:
    HAS_SERIAL = False
    print("Warning: pyserial not installed, serial detection limited")


def detect_serial_devices() -> list[dict]:
    """Detect available USB-to-serial devices."""
    devices = []
    
    if HAS_SERIAL:
        for port in serial.tools.list_ports.comports():
            devices.append({
                "device": port.device,
                "vid": f"0x{port.vid:04X}" if port.vid else None,
                "pid": f"0x{port.pid:04X}" if port.pid else None,
                "manufacturer": port.manufacturer,
                "product": port.product,
                "description": port.description or "Unknown",
            })
    else:
        # Fallback: check /dev/tty*
        import subprocess
        try:
            result = subprocess.run(
                ["ls", "-la", "/dev/ttyACM*", "/dev/ttyUSB*"],
                capture_output=True,
                text=True,
                timeout=5
            )
            if result.returncode == 0:
                for line in result.stdout.split("\n"):
                    if "ttyACM" in line or "ttyUSB" in line:
                        parts = line.split()
                        if len(parts) >= 10:
                            device = f"/dev/{parts[-1]}"
                            devices.append({
                                "device": device,
                                "vid": None,
                                "pid": None,
                                "manufacturer": None,
                                "product": None,
                                "description": "Detected via ls",
                            })
        except Exception:
            pass
    
    return devices


def suggest_modbus_port(devices: list[dict]) -> Optional[str]:
    """Suggest Modbus serial port from detected devices."""
    # Common Modbus USB adapters
    modbus_keywords = ["modbus", "ftdi", "usb-serial", "ch340", "cp210"]
    
    for device in devices:
        desc_lower = (device.get("description") or "").lower()
        prod_lower = (device.get("product") or "").lower()
        
        for keyword in modbus_keywords:
            if keyword in desc_lower or keyword in prod_lower:
                return device["device"]
    
    # Fallback: return first ACM device (often Arduino/Modbus)
    for device in devices:
        if "ttyACM" in device["device"]:
            return device["device"]
    
    # Fallback: return first USB device
    if devices:
        return devices[0]["device"]
    
    return None


def generate_env_content(
    hardware_mode: str = "real",
    modbus_port: Optional[str] = None,
    piadc_url: str = "http://localhost:8080",
    motor_url: str = "http://localhost:49055",
    lung_motor_url: str = "http://localhost:8205",
) -> str:
    """Generate .env file content."""
    content = """# OqlOS Service Configuration
# Auto-generated by setup_hardware_and_run_oql.py

# Server Configuration
FIRMWARE_PORT=8202
SERVICE_NAME=firmware-simulator
SERVICE_VERSION=0.1.0

# Hardware Mode (mock | real)
HARDWARE_MODE={hardware_mode}

# Modbus RTU Configuration
MODBUS_SERIAL_PORT={modbus_port}
MODBUS_BAUD=19200
MODBUS_PARITY=N
MODBUS_DEVICE_ID=1

# Modbus TCP Fallback
MODBUS_HOST=localhost
MODBUS_PORT=502

# Hardware Service URLs
PIADC_URL={piadc_url}
MOTOR_URL={motor_url}
LUNG_MOTOR_URL={lung_motor_url}

# Pump Calibration
# Flow rate that maps to 100% PWM for pompa 1
PUMP_FLOW_FULL_SCALE_LPM=10

# Logging (DEBUG | INFO | WARNING | ERROR)
LOG_LEVEL=INFO

# CORS Settings (comma-separated origins or * for all)
CORS_ORIGINS=*
"""
    return content.format(
        hardware_mode=hardware_mode,
        modbus_port=modbus_port or "/dev/ttyACM1",
        piadc_url=piadc_url,
        motor_url=motor_url,
        lung_motor_url=lung_motor_url,
    )


def setup_env_file(
    env_path: Path,
    hardware_mode: str = "real",
    modbus_port: Optional[str] = None,
    force: bool = False,
) -> bool:
    """Setup .env file with hardware configuration."""
    if env_path.exists() and not force:
        print(f".env file already exists at {env_path}")
        print("Use --force to overwrite")
        return False
    
    # Detect hardware if not provided
    if hardware_mode == "real" and modbus_port is None:
        devices = detect_serial_devices()
        print(f"\nDetected {len(devices)} serial device(s):")
        for i, dev in enumerate(devices, 1):
            print(f"  {i}. {dev['device']}: {dev['description']}")
        
        modbus_port = suggest_modbus_port(devices)
        if modbus_port:
            print(f"\nSuggested Modbus port: {modbus_port}")
        else:
            print("\nNo suitable Modbus port detected, using default /dev/ttyACM1")
            modbus_port = "/dev/ttyACM1"
    
    # Generate and write .env
    content = generate_env_content(
        hardware_mode=hardware_mode,
        modbus_port=modbus_port,
    )
    
    env_path.write_text(content)
    print(f"\n✓ Created .env file at {env_path}")
    print(f"  Hardware mode: {hardware_mode}")
    print(f"  Modbus port: {modbus_port}")
    return True


def load_env_file(env_path: Path) -> None:
    """Load .env file into environment variables."""
    if not env_path.exists():
        print(f"Error: .env file not found at {env_path}")
        sys.exit(1)
    
    # Parse .env file
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            os.environ[key.strip()] = value.strip()
    
    print(f"✓ Loaded .env from {env_path}")


def run_oql_scenario(
    scenario_path: Path,
    mode: str = "execute",
    firmware_url: Optional[str] = None,
) -> int:
    """Run OQL scenario with loaded configuration."""
    from oqlos.core.interpreter import CqlInterpreter
    
    # Get firmware URL from env or parameter
    if firmware_url is None:
        firmware_url = os.environ.get(
            "FIRMWARE_URL",
            f"http://localhost:{os.environ.get('FIRMWARE_PORT', '8202')}"
        )
    
    print(f"\n{'='*60}")
    print(f"Running OQL scenario: {scenario_path.name}")
    print(f"Mode: {mode}")
    print(f"Firmware URL: {firmware_url}")
    print(f"Hardware mode: {os.environ.get('HARDWARE_MODE', 'mock')}")
    print(f"{'='*60}\n")
    
    # Read scenario
    source = scenario_path.read_text(encoding="utf-8")
    
    # Create interpreter
    interpreter = CqlInterpreter(
        mode=mode,
        firmware_url=firmware_url,
    )
    
    # Run scenario
    result = interpreter.run(source, scenario_path.name)
    
    # Print result
    print(f"\n{'='*60}")
    print(f"Result: {'✓ PASSED' if result.ok else '✗ FAILED'}")
    print(f"Steps: {len(result.steps)}")
    print(f"Duration: {result.duration_ms:.1f}ms")
    if result.errors:
        print(f"Errors: {len(result.errors)}")
        for error in result.errors:
            print(f"  - {error}")
    if result.warnings:
        print(f"Warnings: {len(result.warnings)}")
        for warning in result.warnings:
            print(f"  - {warning}")
    print(f"{'='*60}\n")
    
    return 0 if result.ok else 1


def main():
    parser = argparse.ArgumentParser(
        description="Setup hardware configuration and run OQL scenarios"
    )
    parser.add_argument(
        "scenario",
        type=Path,
        help="OQL scenario file to run"
    )
    parser.add_argument(
        "--mode",
        choices=["validate", "dry-run", "execute"],
        default="execute",
        help="Execution mode (default: execute)"
    )
    parser.add_argument(
        "--hardware-mode",
        choices=["mock", "real"],
        default="real",
        help="Hardware mode (default: real)"
    )
    parser.add_argument(
        "--modbus-port",
        help="Explicit Modbus serial port (auto-detected if not specified)"
    )
    parser.add_argument(
        "--firmware-url",
        help="Override firmware service URL"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing .env file"
    )
    parser.add_argument(
        "--env-path",
        type=Path,
        default=Path(__file__).parent / ".env",
        help="Path to .env file (default: .env in script directory)"
    )
    
    args = parser.parse_args()
    
    # Validate scenario file
    if not args.scenario.exists():
        print(f"Error: Scenario file not found: {args.scenario}")
        sys.exit(1)
    
    # Setup .env file
    if not setup_env_file(
        args.env_path,
        hardware_mode=args.hardware_mode,
        modbus_port=args.modbus_port,
        force=args.force,
    ):
        # .env already exists, just load it
        load_env_file(args.env_path)
    else:
        # New .env created, load it
        load_env_file(args.env_path)
    
    # Run OQL scenario
    exit_code = run_oql_scenario(
        args.scenario,
        mode=args.mode,
        firmware_url=args.firmware_url,
    )
    
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
