flowchart LR
    subgraph oqlos__api
        oqlos__api__execution__execution_logs_stream["execution_logs_stream"]
        oqlos__api__state__stream_values["stream_values"]
        oqlos__api__state___extract_inline_dsl["_extract_inline_dsl"]
        oqlos__api__scenarios___compute_slug["_compute_slug"]
        oqlos__api__state___generate_sinusoidal_values["_generate_sinusoidal_values"]
        oqlos__api__scenarios___extract_display_fields["_extract_display_fields"]
        oqlos__api__plugins__disconnect_plugin["disconnect_plugin"]
        oqlos__api__plugins__get_plugin_info["get_plugin_info"]
        oqlos__api__scenarios___extract_goals["_extract_goals"]
        oqlos__api__logs__get_log_stats["get_log_stats"]
        oqlos__api__state___compose_named_state["_compose_named_state"]
        oqlos__api__hardware__set_valve["set_valve"]
        oqlos__api__plugins__list_plugins["list_plugins"]
        oqlos__api__plugins__validate_plugin_configs["validate_plugin_configs"]
        oqlos__api__state__fetch_variables["fetch_variables"]
        oqlos__api__scenarios___fetch_raw_from_sources["_fetch_raw_from_sources"]
        oqlos__api__editor__execute_scenario["execute_scenario"]
        oqlos__api__scenarios__fetch_scenarios["fetch_scenarios"]
        oqlos__api__state__get_variables_alias["get_variables_alias"]
        oqlos__api__scenarios___merge_goals_into_scenario["_merge_goals_into_scenario"]
        oqlos__api__plugins__connect_plugin["connect_plugin"]
        oqlos__api__execution___build_step_labels["_build_step_labels"]
        oqlos__api__editor__read_file_endpoint["read_file_endpoint"]
        oqlos__api__scenarios___normalize_scenario_row["_normalize_scenario_row"]
        oqlos__api__editor__write_file_endpoint["write_file_endpoint"]
        oqlos__api__main__editor_page["editor_page"]
        oqlos__api__hardware__set_lung["set_lung"]
        oqlos__api__plugins__get_plugin_status["get_plugin_status"]
        oqlos__api__execution___resolve_current_index["_resolve_current_index"]
        oqlos__api__hardware___probe_tic249["_probe_tic249"]
        oqlos__api__execution__execution_stream["execution_stream"]
        oqlos__api__plugins__get_plugin_health["get_plugin_health"]
        oqlos__api__main__index_page["index_page"]
        oqlos__api__hardware___gw["_gw"]
        oqlos__api__scenarios__register_dsl["register_dsl"]
        oqlos__api__execution___resolve_step_label["_resolve_step_label"]
        oqlos__api__logs___get_service["_get_service"]
        oqlos__api__editor___safe_path["_safe_path"]
        oqlos__api__scenarios___parse_goals_from_dsl["_parse_goals_from_dsl"]
        oqlos__api__hardware__set_pump["set_pump"]
        oqlos__api__state___handle_start["_handle_start"]
        oqlos__api__scenarios___extract_id["_extract_id"]
        oqlos__api__hardware__stop_lung["stop_lung"]
        oqlos__api__scenarios___register_single_dsl_scenario["_register_single_dsl_scenario"]
        oqlos__api__hardware___probe_dri0050["_probe_dri0050"]
        oqlos__api__state___extract_scenario_id["_extract_scenario_id"]
        oqlos__api__state__get_sim_state["get_sim_state"]
        oqlos__api__scenarios___normalize_dsl_payload["_normalize_dsl_payload"]
        oqlos__api__state___compose_sim_state_list["_compose_sim_state_list"]
        oqlos__api__execution__start_execution["start_execution"]
        oqlos__api__state___maybe_register_dsl_from_content["_maybe_register_dsl_from_conte"]
        oqlos__api__scenarios__get_scenario["get_scenario"]
        oqlos__api__execution___current_projection["_current_projection"]
        oqlos__api__hardware__hardware_health["hardware_health"]
        oqlos__api__execution__get_execution_projection["get_execution_projection"]
        oqlos__api__execution___register_dsl_scenario["_register_dsl_scenario"]
        oqlos__api__scenarios___collect_dsl_strings["_collect_dsl_strings"]
        oqlos__api__scenarios___parse_content_to_goals["_parse_content_to_goals"]
        oqlos__api__logs__get_logs["get_logs"]
        oqlos__api__hardware___probe_i2c_ads1115["_probe_i2c_ads1115"]
        oqlos__api__state__get_state["get_state"]
        oqlos__api__hardware___collect_hardware_diagnostics["_collect_hardware_diagnostics"]
        oqlos__api__editor__list_files["list_files"]
        oqlos__api__hardware__read_sensor["read_sensor"]
        oqlos__api__plugins__execute_plugin_command["execute_plugin_command"]
        oqlos__api__scenarios___ensure_list["_ensure_list"]
        oqlos__api__hardware___probe_modbus_rtu["_probe_modbus_rtu"]
        oqlos__api__hardware___scan_usb_devices["_scan_usb_devices"]
        oqlos__api__hardware___probe_all_hardware["_probe_all_hardware"]
    end
    subgraph oqlos__config
        oqlos__config__get_settings["get_settings"]
    end
    subgraph oqlos__core
        oqlos__core___dsl_helpers___map_peripheral["_map_peripheral"]
        oqlos__core___cql_tokenizer___try_save["_try_save"]
        oqlos__core___line_parsers___parse_inline_task["_parse_inline_task"]
        oqlos__core___line_parsers___parse_pump_line["_parse_pump_line"]
        oqlos__core__safe_eval__safe_eval["safe_eval"]
        oqlos__core__parser___parse_runtime_line["_parse_runtime_line"]
        oqlos__core___line_parsers___set_lung_step["_set_lung_step"]
        oqlos__core___dsl_helpers___map_action_value["_map_action_value"]
        oqlos__core___interpreter_actions___mark_success["_mark_success"]
        oqlos__core__executor___safe_resolve["_safe_resolve"]
        oqlos__core___interpreter_actions___mock_api_response["_mock_api_response"]
        oqlos__core___cql_tokenizer___try_if_else["_try_if_else"]
        oqlos__core___cql_tokenizer___try_if_standalone["_try_if_standalone"]
        oqlos__core__cql_parser___collect_all_goals["_collect_all_goals"]
        oqlos__core__parser__parse_dsl_to_goal["parse_dsl_to_goal"]
        oqlos__core__executor___resolve_name_or_attr["_resolve_name_or_attr"]
        oqlos__core___interpreter_actions___drop_command_token["_drop_command_token"]
        oqlos__core__executor__safe_eval_condition["safe_eval_condition"]
        oqlos__core___cql_tokenizer___try_min_max["_try_min_max"]
        oqlos__core___cql_tokenizer___try_goto["_try_goto"]
        oqlos__core__safe_eval___eval_unary_op["_eval_unary_op"]
        oqlos__core___func_resolver___extract_func_name["_extract_func_name"]
        oqlos__core___compare__resolve_compare_chain["resolve_compare_chain"]
        oqlos__core___interpreter_actions__exec_action_assert["exec_action_assert"]
        oqlos__core__parser__parse_dsl_to_goal_with_issues["parse_dsl_to_goal_with_issues"]
        oqlos__core___cql_tokenizer___parse_condition_value["_parse_condition_value"]
        oqlos__core___cql_tokenizer___try_set["_try_set"]
        oqlos__core___line_parsers___parse_action_line["_parse_action_line"]
        oqlos__core__executor__ScenarioOrchestrator__validate_goal["validate_goal"]
        oqlos__core__cql_parser___ParseState___try_hierarchy["_try_hierarchy"]
        oqlos__core__safe_eval___eval_if_exp["_eval_if_exp"]
        oqlos__core___line_parsers___set_pump_step["_set_pump_step"]
        oqlos__core___interpreter_actions___coerce_expected_value["_coerce_expected_value"]
        oqlos__core___line_parsers___parse_if_condition["_parse_if_condition"]
        oqlos__core__interpreter__CqlInterpreter__parse["parse"]
        oqlos__core__safe_eval___eval_call["_eval_call"]
        oqlos__core___interpreter_actions__exec_action_shell["exec_action_shell"]
        oqlos__core___interpreter_actions__exec_action_func["exec_action_func"]
        oqlos__core___value_normalizers__ValueNormalizer__coerce_float["coerce_float"]
        oqlos__core___interpreter_actions___do_sleep["_do_sleep"]
        oqlos__core___interpreter_actions__exec_action_val["exec_action_val"]
        oqlos__core___interpreter_actions__exec_action_api["exec_action_api"]
        oqlos__core__base__InterpreterOutput__output_yaml["output_yaml"]
        oqlos__core___dsl_helpers___map_wait_action["_map_wait_action"]
        oqlos__core___func_resolver___guard_recursion["_guard_recursion"]
        oqlos__core___line_parsers___parse_task_part["_parse_task_part"]
        oqlos__core__safe_eval___eval_bool_op["_eval_bool_op"]
        oqlos__core___cql_tokenizer___try_if_block["_try_if_block"]
        oqlos__core___func_resolver___parse_func_call["_parse_func_call"]
        oqlos__core__safe_eval___eval_bin_op["_eval_bin_op"]
        oqlos__core__interpreter__CqlInterpreter__execute["execute"]
        oqlos__core___interpreter_actions___exec_set_wait["_exec_set_wait"]
        oqlos__core___dsl_helpers___map_valve_action["_map_valve_action"]
        oqlos__core___compare__resolve_compare["resolve_compare"]
        oqlos__core___dsl_helpers___looks_like_lung_object["_looks_like_lung_object"]
        oqlos__core___dsl_helpers___parse_numeric_value["_parse_numeric_value"]
        oqlos__core__base__VariableStore__set["set"]
        oqlos__core___interpreter_actions___record_failure["_record_failure"]
        oqlos__core__cql_parser__parse_cql["parse_cql"]
        oqlos__core___dsl_helpers___looks_like_pump_object["_looks_like_pump_object"]
        oqlos__core___interpreter_actions__exec_action_expect["exec_action_expect"]
        oqlos__core___interpreter_actions__exec_action_save["exec_action_save"]
        oqlos__core__parser___dispatch_simple_parser["_dispatch_simple_parser"]
        oqlos__core___func_resolver___collect_function_definitions["_collect_function_definitions"]
        oqlos__core__interpreter__CqlInterpreter___build_script_result["_build_script_result"]
        oqlos__core__base__VariableStore__all["all"]
        oqlos__core___interpreter_actions__parse_wait_secs["parse_wait_secs"]
        oqlos__core__interpreter__CqlInterpreter___exec_flat_action["_exec_flat_action"]
        oqlos__core___dsl_helpers___looks_like_sensor_object["_looks_like_sensor_object"]
        oqlos__core___line_parsers___set_valve_step["_set_valve_step"]
        oqlos__core___dsl_helpers___map_pump_action["_map_pump_action"]
        oqlos__core___cql_tokenizer___match_first["_match_first"]
        oqlos__core___interpreter_actions___get_nested_value["_get_nested_value"]
        oqlos__core__executor__ScenarioOrchestrator___execute_validate_step["_execute_validate_step"]
        oqlos__core___line_parsers___parse_set_line["_parse_set_line"]
        oqlos__core__safe_eval___eval_compare["_eval_compare"]
        oqlos__core___interpreter_actions___extract_action_tokens["_extract_action_tokens"]
        oqlos__core___cql_tokenizer___try_val["_try_val"]
        oqlos__core__cql_parser___validate_intervals["_validate_intervals"]
        oqlos__core___dsl_helpers___map_lung_action["_map_lung_action"]
        oqlos__core__cql_parser__validate_cql["validate_cql"]
        oqlos__core__safe_eval___eval_node["_eval_node"]
        oqlos__core___interpreter_actions__exec_action_wait["exec_action_wait"]
        oqlos__core___interpreter_actions__exec_action_set["exec_action_set"]
        oqlos__core___dsl_helpers___normalize_quote_syntax["_normalize_quote_syntax"]
        oqlos__core___interpreter_actions__exec_action_min_max["exec_action_min_max"]
        oqlos__core___interpreter_actions___resolve_numeric_token["_resolve_numeric_token"]
        oqlos__core__parser___try_action_or_condition["_try_action_or_condition"]
        oqlos__core___interpreter_actions___compare_values["_compare_values"]
        oqlos__core__executor___resolve_compare["_resolve_compare"]
        oqlos__core___dsl_helpers___looks_like_valve_object["_looks_like_valve_object"]
    end
    subgraph oqlos__dsl
        oqlos__dsl__schema___build_inferred_param_unit_map["_build_inferred_param_unit_map"]
        oqlos__dsl__schema__get_default_dsl_schema["get_default_dsl_schema"]
        oqlos__dsl__schema___merge_param_unit_map["_merge_param_unit_map"]
        oqlos__dsl__schema___merge_object_function_map["_merge_object_function_map"]
        oqlos__dsl__schema___normalize_name_list["_normalize_name_list"]
        oqlos__dsl__schema___build_inferred_object_function_map["_build_inferred_object_functio"]
    end
    subgraph oqlos__hardware
        oqlos__hardware__discovery___try_modbus_connection["_try_modbus_connection"]
        oqlos__hardware__plugins__registry__PluginRegistry__create_instance["create_instance"]
        oqlos__hardware__firmware_adapter__FirmwareAdapter___handle_pump_action["_handle_pump_action"]
        oqlos__hardware__plugins__motor__MotorPlugin__disconnect["disconnect"]
        oqlos__hardware__firmware_adapter__FirmwareAdapter____init__["__init__"]
        oqlos__hardware__firmware_adapter__FirmwareAdapter___handle_lung_action["_handle_lung_action"]
        oqlos__hardware__gateway___ModbusAdapter____init__["__init__"]
        oqlos__hardware__discovery__list_serial_ports["list_serial_ports"]
        oqlos__hardware__discovery___build_probe_candidates["_build_probe_candidates"]
        oqlos__hardware__plugin_gateway__PluginHardwareGateway___load_hardware_schema["_load_hardware_schema"]
        oqlos__hardware__plugin_gateway__PluginHardwareGateway__health["health"]
        oqlos__hardware__plugins__lung__LungPlugin__health_check["health_check"]
        oqlos__hardware__plugins__registry__PluginRegistry__discover_entry_point_plugins["discover_entry_point_plugins"]
        oqlos__hardware__plugin_gateway__PluginHardwareGateway__reload_configs["reload_configs"]
        oqlos__hardware__firmware_adapter__FirmwareAdapter___get_lung_motor_url["_get_lung_motor_url"]
        oqlos__hardware__plugin_gateway__PluginHardwareGateway___initialize_plugins["_initialize_plugins"]
        oqlos__hardware__plugins___shared__not_connected_health["not_connected_health"]
        oqlos__hardware__plugins__piadc__PiadcPlugin__health_check["health_check"]
        oqlos__hardware__plugins__registry__PluginRegistry__validate_all_configurations["validate_all_configurations"]
        oqlos__hardware__discovery___make_pymodbus_fallback_result["_make_pymodbus_fallback_result"]
        oqlos__hardware__plugins__registry__PluginRegistry__disconnect_plugin["disconnect_plugin"]
        oqlos__hardware__firmware_adapter___parse_numeric["_parse_numeric"]
        oqlos__hardware__discovery__probe_waveshare_modbus["probe_waveshare_modbus"]
        oqlos__hardware__plugins__base__get_pluggy_manager["get_pluggy_manager"]
        oqlos__hardware__plugins__registry__PluginRegistry__get_instance["get_instance"]
        oqlos__hardware__discovery___make_probe_failure_result["_make_probe_failure_result"]
        oqlos__hardware__plugin_gateway__PluginHardwareGateway____init__["__init__"]
        oqlos__hardware__plugins__registry__PluginRegistry__load_configs_from_yaml["load_configs_from_yaml"]
        oqlos__hardware__plugins__registry__PluginRegistry__get_plugin_class["get_plugin_class"]
        oqlos__hardware__discovery___unique_preserving_order["_unique_preserving_order"]
        oqlos__hardware__plugins__piadc__PiadcPlugin__disconnect["disconnect"]
        oqlos__hardware__config_schema__load_config_from_yaml["load_config_from_yaml"]
        oqlos__hardware__plugins__lung__LungPlugin__disconnect["disconnect"]
        oqlos__hardware__plugins__motor__MotorPlugin__health_check["health_check"]
        oqlos__hardware__plugins__registry__PluginRegistry__list_plugins["list_plugins"]
        oqlos__hardware__plugins___shared__health_check_exception["health_check_exception"]
        oqlos__hardware__plugins___shared__http_disconnect["http_disconnect"]
        oqlos__hardware__plugins__registry__PluginRegistry__connect_plugin["connect_plugin"]
        oqlos__hardware__discovery___make_probe_success_result["_make_probe_success_result"]
        oqlos__hardware__plugins___shared__http_health_check["http_health_check"]
        oqlos__hardware__plugins__registry__PluginRegistry__get_status["get_status"]
        oqlos__hardware__config_schema__get_hardware_config["get_hardware_config"]
        oqlos__hardware__plugin_gateway__PluginHardwareGateway___create_default_configs["_create_default_configs"]
        oqlos__hardware__plugins__registry__PluginRegistry__health_check["health_check"]
        oqlos__hardware__firmware_adapter__FirmwareAdapter__set_peripheral["set_peripheral"]
        oqlos__hardware__plugin_gateway__PluginHardwareGateway___load_plugin_configs["_load_plugin_configs"]
        oqlos__hardware__plugins__registry__PluginRegistry__health_check_all["health_check_all"]
    end
    subgraph oqlos__shared
        oqlos__shared__version_endpoint__build_version_payload["build_version_payload"]
        oqlos__shared__config_factory__create_nfo_setup["create_nfo_setup"]
        oqlos__shared__file_ops__write_file["write_file"]
        oqlos__shared__file_ops___ensure_safe_path["_ensure_safe_path"]
        oqlos__shared__event_server__ConnectionManager____init__["__init__"]
        oqlos__shared__release_version__clean_version["clean_version"]
        oqlos__shared__logs_query__resolve_logs_db_path["resolve_logs_db_path"]
        oqlos__shared__release_version__main["main"]
        oqlos__shared__release_version___read_version_from_package_json["_read_version_from_package_jso"]
        oqlos__shared__file_ops__read_file["read_file"]
        oqlos__shared__version_endpoint__create_version_router["create_version_router"]
        oqlos__shared__release_version___read_version_from_text["_read_version_from_text"]
        oqlos__shared__release_version__resolve_release_version["resolve_release_version"]
        oqlos__shared__release_version___version_candidates["_version_candidates"]
        oqlos__shared__release_version___run_git["_run_git"]
        oqlos__shared___endpoint_helpers__serve_html_page["serve_html_page"]
        oqlos__shared__file_ops__iter_entries["iter_entries"]
    end
    subgraph oqlos__tools
        oqlos__tools__xml_import__generators___build_steps_from_op["_build_steps_from_op"]
        oqlos__tools__cql_cli__preflight___emit_text_preflight["_emit_text_preflight"]
        oqlos__tools__cql_cli__preflight__ensure_firmware_running["ensure_firmware_running"]
        oqlos__tools__hardware_diagnose__benchmark__run_benchmark["run_benchmark"]
        oqlos__tools__cql_cli__main__run_cmd_mode["run_cmd_mode"]
        oqlos__tools__hardware_diagnose____main_____print_list["_print_list"]
        oqlos__tools__hardware_diagnose__shell___cmd_list["_cmd_list"]
        oqlos__tools__cql_cli__commands__run_single_command["run_single_command"]
        oqlos__tools__cql_cli__main__run_file_mode["run_file_mode"]
        oqlos__tools__cql_cli___sync_compat_symbols["_sync_compat_symbols"]
        oqlos__tools__xml_import__generators___generate_cql_for_goal["_generate_cql_for_goal"]
        oqlos__tools__cql_cli__preflight___start_firmware_service["_start_firmware_service"]
        oqlos__tools__hardware_diagnose__shell__interactive_shell["interactive_shell"]
        oqlos__tools__plugin_cli__cmd_execute["cmd_execute"]
        oqlos__tools__hardware_diagnose__health__check_firmware_identify["check_firmware_identify"]
        oqlos__tools__plugin_cli__cmd_disconnect["cmd_disconnect"]
        oqlos__tools__hardware_diagnose__calibration___calibrate_pump["_calibrate_pump"]
        oqlos__tools__cql_cli__main__create_cmd_parser["create_cmd_parser"]
        oqlos__tools__hardware_diagnose__health__cmd_diagnose["cmd_diagnose"]
        oqlos__tools__hardware_diagnose__discovery___run_shell_command["_run_shell_command"]
        oqlos__tools__cql_cli__utils__build_single_command_scenario["build_single_command_scenario"]
        oqlos__tools__xml_import___utils__normalize_output_name["normalize_output_name"]
        oqlos__tools__xml_import__generators___emit_dsl_param["_emit_dsl_param"]
        oqlos__tools__hardware_diagnose__shell___cmd_benchmark["_cmd_benchmark"]
        oqlos__tools__hardware_diagnose__report__save_diagnostic_report["save_diagnostic_report"]
        oqlos__tools__cql_cli__utils__normalize_target_name["normalize_target_name"]
        oqlos__tools__cql_cli__utils__build_result_payload["build_result_payload"]
        oqlos__tools__plugin_cli___load_config_file["_load_config_file"]
        oqlos__tools__cql_cli__preflight__emit_preflight_success["emit_preflight_success"]
        oqlos__tools__xml_import___utils__is_pump_output["is_pump_output"]
        oqlos__tools__hardware_diagnose__discovery__list_i2c_buses["list_i2c_buses"]
        oqlos__tools__plugin_cli__cmd_list["cmd_list"]
        oqlos__tools__hardware_diagnose__health__cmd_health["cmd_health"]
        oqlos__tools__plugin_cli__cmd_status["cmd_status"]
        oqlos__tools__cql_cli__utils__parse_sensor_overrides["parse_sensor_overrides"]
        oqlos__tools__xml_import__generators___emit_cql_output["_emit_cql_output"]
        oqlos__tools__hardware_diagnose__calibration__run_calibration_test["run_calibration_test"]
        oqlos__tools__hardware_diagnose__health___request_firmware_json["_request_firmware_json"]
        oqlos__tools__hardware_diagnose__health__check_firmware_health["check_firmware_health"]
        oqlos__tools__hardware_diagnose____main_____print_benchmark["_print_benchmark"]
        oqlos__tools__cql_cli__commands__run_source["run_source"]
        oqlos__tools__cql_cli__preflight___emit_preflight_error["_emit_preflight_error"]
        oqlos__tools__plugin_cli__cmd_connect["cmd_connect"]
        oqlos__tools__cql_cli__commands__handle_list_command["handle_list_command"]
        oqlos__tools__xml_import__generators___format_range["_format_range"]
        oqlos__tools__hardware_diagnose__discovery__list_usb_serial_devices["list_usb_serial_devices"]
        oqlos__tools__hardware_diagnose__calibration___calibrate_valves["_calibrate_valves"]
        oqlos__tools__xml_import__generators__generate_goals_json["generate_goals_json"]
        oqlos__tools__cql_cli__main__main["main"]
        oqlos__tools__plugin_cli__cmd_reload["cmd_reload"]
        oqlos__tools__xml_import__generators___emit_dsl_sensors["_emit_dsl_sensors"]
        oqlos__tools__xml_import__parser___populate_report_fields["_populate_report_fields"]
        oqlos__tools__xml_import__generators___mode_action["_mode_action"]
        oqlos__tools__hardware_diagnose__calibration___calibrate_sensors["_calibrate_sensors"]
        oqlos__tools__cql_cli__commands___run_continuous_mode["_run_continuous_mode"]
        oqlos__tools__xml_import__generators___emit_cql_param["_emit_cql_param"]
        oqlos__tools__hardware_diagnose____main_____print_health["_print_health"]
        oqlos__tools__xml_import__parser___parse_test_run["_parse_test_run"]
        oqlos__tools__xml_import__generators__generate_dsl["generate_dsl"]
        oqlos__tools__hardware_diagnose__discovery__detect_chips_on_i2c["detect_chips_on_i2c"]
        oqlos__tools__xml_import__generators___emit_cql_sensor_param["_emit_cql_sensor_param"]
        oqlos__tools__plugin_cli__cmd_validate["cmd_validate"]
        oqlos__tools__cql_cli__main__create_file_parser["create_file_parser"]
        oqlos__tools__xml_import__generators___append_sensor_assertion["_append_sensor_assertion"]
        oqlos__tools__cql_cli__utils___resolve_sensor_target["_resolve_sensor_target"]
        oqlos__tools__cql_cli__commands__execute_command_with_cleanup["execute_command_with_cleanup"]
        oqlos__tools__cql_cli__preflight__check_required_adapter["check_required_adapter"]
        oqlos__tools__plugin_cli__cmd_capabilities["cmd_capabilities"]
        oqlos__tools__xml_import___utils__is_compressor_output["is_compressor_output"]
        oqlos__tools__plugin_cli__cmd_health["cmd_health"]
        oqlos__tools__cql_cli__utils__validate_directory["validate_directory"]
        oqlos__tools__xml_import__generators___build_validation_criteria["_build_validation_criteria"]
        oqlos__tools__xml_import__parser__parse_xml["parse_xml"]
        oqlos__tools__hardware_diagnose__shell___cmd_calibrate["_cmd_calibrate"]
        oqlos__tools__xml_import__parser___parse_intervals["_parse_intervals"]
        oqlos__tools__cql_cli__preflight___emit_yaml_preflight["_emit_yaml_preflight"]
        oqlos__tools__xml_import__parser___parse_operation["_parse_operation"]
        oqlos__tools__hardware_diagnose__shell___dispatch_command["_dispatch_command"]
        oqlos__tools__hardware_diagnose____main_____print_calibrate["_print_calibrate"]
        oqlos__tools__cql_cli__preflight__check_firmware_state["check_firmware_state"]
        oqlos__tools__cql_cli__preflight___is_firmware_running["_is_firmware_running"]
        oqlos__tools__cql_cli__utils___extract_first_action["_extract_first_action"]
        oqlos__tools__hardware_diagnose__report__format_peripheral_table["format_peripheral_table"]
        oqlos__tools__plugin_cli__cmd_peripherals["cmd_peripherals"]
        oqlos__tools__cql_cli__utils__resolve_required_adapter["resolve_required_adapter"]
        oqlos__tools__xml_import__parser___parse_operation_params["_parse_operation_params"]
        oqlos__tools__cql_cli__utils___resolve_peripheral_adapter["_resolve_peripheral_adapter"]
        oqlos__tools__cql_cli__preflight__preflight_hardware["preflight_hardware"]
        oqlos__tools__cql_cli__main["main"]
    end
    subgraph setup_hardware_and_run_oql
        setup_hardware_and_run_oql__main["main"]
        setup_hardware_and_run_oql__generate_env_content["generate_env_content"]
        setup_hardware_and_run_oql__detect_serial_devices["detect_serial_devices"]
        setup_hardware_and_run_oql__setup_env_file["setup_env_file"]
        setup_hardware_and_run_oql__run_oql_scenario["run_oql_scenario"]
    end
    setup_hardware_and_run_oql__setup_env_file --> setup_hardware_and_run_oql__generate_env_content
    setup_hardware_and_run_oql__setup_env_file --> setup_hardware_and_run_oql__detect_serial_devices
    setup_hardware_and_run_oql__main --> setup_hardware_and_run_oql__run_oql_scenario
    oqlos__core___dsl_helpers___map_peripheral --> oqlos__core___dsl_helpers___looks_like_valve_object
    oqlos__core___dsl_helpers___map_peripheral --> oqlos__core___dsl_helpers___looks_like_pump_object
    oqlos__core___dsl_helpers___map_peripheral --> oqlos__core___dsl_helpers___looks_like_lung_object
    oqlos__core___dsl_helpers___map_peripheral --> oqlos__core___dsl_helpers___looks_like_sensor_object
    oqlos__core___dsl_helpers___map_pump_action --> oqlos__core___dsl_helpers___parse_numeric_value
    oqlos__core___dsl_helpers___map_lung_action --> oqlos__core___dsl_helpers___parse_numeric_value
    oqlos__core___dsl_helpers___map_action_value --> oqlos__core___dsl_helpers___looks_like_valve_object
    oqlos__core___dsl_helpers___map_action_value --> oqlos__core___dsl_helpers___looks_like_pump_object
    oqlos__core___dsl_helpers___map_action_value --> oqlos__core___dsl_helpers___looks_like_lung_object
    oqlos__core___dsl_helpers___map_action_value --> oqlos__core___dsl_helpers___map_valve_action
    oqlos__core___dsl_helpers___map_action_value --> oqlos__core___dsl_helpers___map_pump_action
    oqlos__core___dsl_helpers___map_action_value --> oqlos__core___dsl_helpers___map_lung_action
    oqlos__core___dsl_helpers___map_action_value --> oqlos__core___dsl_helpers___looks_like_sensor_object
    oqlos__core___dsl_helpers___map_action_value --> oqlos__core___dsl_helpers___map_wait_action
    oqlos__core___interpreter_actions___drop_command_token --> oqlos__core___interpreter_actions___extract_action_tokens
    oqlos__core___interpreter_actions___compare_values --> oqlos__core___interpreter_actions___coerce_expected_value
    oqlos__core___interpreter_actions__exec_action_wait --> oqlos__core___interpreter_actions__parse_wait_secs
    oqlos__core___interpreter_actions__exec_action_wait --> oqlos__core___interpreter_actions___do_sleep
    oqlos__core___interpreter_actions__exec_action_func --> oqlos__core___interpreter_actions___resolve_numeric_token
    oqlos__core___interpreter_actions__exec_action_api --> oqlos__core___interpreter_actions___mock_api_response
    oqlos__core___interpreter_actions__exec_action_expect --> oqlos__core___interpreter_actions___drop_command_token
    oqlos__core___interpreter_actions__exec_action_expect --> oqlos__core___interpreter_actions___mark_success
    oqlos__core___interpreter_actions__exec_action_assert --> oqlos__core___interpreter_actions___drop_command_token
    oqlos__core___interpreter_actions__exec_action_assert --> oqlos__core___interpreter_actions___record_failure
    oqlos__core___interpreter_actions__exec_action_assert --> oqlos__core___interpreter_actions___get_nested_value
    oqlos__core___interpreter_actions__exec_action_shell --> oqlos__core___interpreter_actions___drop_command_token
    oqlos__core___interpreter_actions__exec_action_shell --> oqlos__core___interpreter_actions___record_failure
    oqlos__core___interpreter_actions__exec_action_set --> oqlos__core___interpreter_actions___exec_set_wait
    oqlos__core___interpreter_actions___exec_set_wait --> oqlos__core___interpreter_actions__parse_wait_secs
    oqlos__core___interpreter_actions___exec_set_wait --> oqlos__core___interpreter_actions___do_sleep
    oqlos__core__parser___dispatch_simple_parser --> oqlos__core___line_parsers___parse_task_part
    oqlos__core__parser___dispatch_simple_parser --> oqlos__core___line_parsers___parse_set_line
    oqlos__core__parser___dispatch_simple_parser --> oqlos__core___line_parsers___parse_pump_line
    oqlos__core__parser___try_action_or_condition --> oqlos__core___line_parsers___parse_action_line
    oqlos__core__parser___try_action_or_condition --> oqlos__core___line_parsers___parse_if_condition
    oqlos__core__parser___parse_runtime_line --> oqlos__core___dsl_helpers___normalize_quote_syntax
    oqlos__core__parser___parse_runtime_line --> oqlos__core___func_resolver___parse_func_call
    oqlos__core__parser___parse_runtime_line --> oqlos__core__parser___try_action_or_condition
    oqlos__core__parser___parse_runtime_line --> oqlos__core___line_parsers___parse_inline_task
    oqlos__core__parser__parse_dsl_to_goal_with_issues --> oqlos__core___func_resolver___collect_function_definitions
    oqlos__core__parser__parse_dsl_to_goal_with_issues --> oqlos__core__parser___parse_runtime_line
    oqlos__core__parser__parse_dsl_to_goal --> oqlos__core__parser__parse_dsl_to_goal_with_issues
    oqlos__core___func_resolver___extract_func_name --> oqlos__core___dsl_helpers___normalize_quote_syntax
    oqlos__core___func_resolver___parse_func_call --> oqlos__core___func_resolver___extract_func_name
    oqlos__core___func_resolver___parse_func_call --> oqlos__core___func_resolver___guard_recursion
    oqlos__core__executor___resolve_compare --> oqlos__core___compare__resolve_compare_chain
    oqlos__core__executor___resolve_compare --> oqlos__core__executor___safe_resolve
    oqlos__core__executor___resolve_name_or_attr --> oqlos__core__executor___safe_resolve
    oqlos__core__executor___safe_resolve --> oqlos__core__executor___resolve_name_or_attr
    oqlos__core__executor__safe_eval_condition --> oqlos__core__executor___safe_resolve
    oqlos__core__executor__ScenarioOrchestrator___execute_validate_step --> oqlos__core__executor__safe_eval_condition
    oqlos__core__executor__ScenarioOrchestrator__validate_goal --> oqlos__core__executor__safe_eval_condition
    oqlos__core___cql_tokenizer___try_save --> oqlos__core___cql_tokenizer___match_first
    oqlos__core___cql_tokenizer___try_set --> oqlos__core___cql_tokenizer___match_first
    oqlos__core___cql_tokenizer___try_if_else --> oqlos__core___cql_tokenizer___match_first
    oqlos__core___cql_tokenizer___try_if_else --> oqlos__core___cql_tokenizer___parse_condition_value
    oqlos__core___cql_tokenizer___try_if_block --> oqlos__core___cql_tokenizer___match_first
    oqlos__core___cql_tokenizer___try_if_block --> oqlos__core___cql_tokenizer___parse_condition_value
    oqlos__core___cql_tokenizer___try_if_standalone --> oqlos__core___cql_tokenizer___try_if_block
    oqlos__core___cql_tokenizer___try_min_max --> oqlos__core___cql_tokenizer___match_first
    oqlos__core___cql_tokenizer___try_val --> oqlos__core___cql_tokenizer___match_first
    oqlos__core___cql_tokenizer___try_goto --> oqlos__core___cql_tokenizer___match_first
    oqlos__core___line_parsers___parse_task_part --> oqlos__core___dsl_helpers___normalize_quote_syntax
    oqlos__core___line_parsers___parse_task_part --> oqlos__core___dsl_helpers___map_peripheral
    oqlos__core___line_parsers___parse_task_part --> oqlos__core___dsl_helpers___map_action_value
    oqlos__core___line_parsers___parse_pump_line --> oqlos__core___dsl_helpers___normalize_quote_syntax
    oqlos__core___line_parsers___parse_pump_line --> oqlos__core___dsl_helpers___parse_numeric_value
    oqlos__core___line_parsers___set_valve_step --> oqlos__core___dsl_helpers___parse_numeric_value
    oqlos__core___line_parsers___set_pump_step --> oqlos__core___dsl_helpers___parse_numeric_value
    oqlos__core___line_parsers___set_lung_step --> oqlos__core___dsl_helpers___parse_numeric_value
    oqlos__core___line_parsers___parse_set_line --> oqlos__core___dsl_helpers___normalize_quote_syntax
    oqlos__core___line_parsers___parse_set_line --> oqlos__core___dsl_helpers___map_peripheral
    oqlos__core___line_parsers___parse_set_line --> oqlos__core___dsl_helpers___parse_numeric_value
    oqlos__core___line_parsers___parse_inline_task --> oqlos__core___line_parsers___parse_task_part
    oqlos__core___line_parsers___parse_action_line --> oqlos__core___dsl_helpers___normalize_quote_syntax
    oqlos__core___line_parsers___parse_action_line --> oqlos__core___dsl_helpers___map_peripheral
    oqlos__core___line_parsers___parse_action_line --> oqlos__core___dsl_helpers___map_action_value
    oqlos__core___line_parsers___parse_if_condition --> oqlos__core___dsl_helpers___normalize_quote_syntax
    oqlos__core__safe_eval__safe_eval --> oqlos__core__safe_eval___eval_node
    oqlos__core__safe_eval___eval_unary_op --> oqlos__core__safe_eval___eval_node
    oqlos__core__safe_eval___eval_bin_op --> oqlos__core__safe_eval___eval_node
    oqlos__core__safe_eval___eval_compare --> oqlos__core___compare__resolve_compare_chain
    oqlos__core__safe_eval___eval_compare --> oqlos__core__safe_eval___eval_node
    oqlos__core__safe_eval___eval_bool_op --> oqlos__core__safe_eval___eval_node
    oqlos__core__safe_eval___eval_bool_op --> oqlos__core__base__VariableStore__all
    oqlos__core__safe_eval___eval_call --> oqlos__core__safe_eval___eval_node
    oqlos__core__safe_eval___eval_if_exp --> oqlos__core__safe_eval___eval_node
    oqlos__core___compare__resolve_compare_chain --> oqlos__core___compare__resolve_compare
    oqlos__core__interpreter__CqlInterpreter__parse --> oqlos__core__cql_parser__parse_cql
    oqlos__core__interpreter__CqlInterpreter___build_script_result --> oqlos__core__base__VariableStore__all
    oqlos__core__interpreter__CqlInterpreter__execute --> oqlos__core__cql_parser__validate_cql
    oqlos__core__interpreter__CqlInterpreter___exec_flat_action --> oqlos__core___interpreter_actions__exec_action_set
    oqlos__core__interpreter__CqlInterpreter___exec_flat_action --> oqlos__core___interpreter_actions__exec_action_val
    oqlos__core__interpreter__CqlInterpreter___exec_flat_action --> oqlos__core___interpreter_actions__exec_action_save
    oqlos__core__interpreter__CqlInterpreter___exec_flat_action --> oqlos__core___interpreter_actions__exec_action_min_max
    oqlos__core__interpreter__CqlInterpreter___exec_flat_action --> oqlos__core___interpreter_actions__exec_action_wait
    oqlos__core__cql_parser___ParseState___try_hierarchy --> oqlos__core___line_parsers___parse_action_line
    oqlos__core__cql_parser__validate_cql --> oqlos__core__cql_parser___collect_all_goals
    oqlos__core__cql_parser__validate_cql --> oqlos__core__cql_parser___validate_intervals
    oqlos__core___value_normalizers__ValueNormalizer__coerce_float --> oqlos__core___dsl_helpers___parse_numeric_value
    oqlos__tools__hardware_diagnose__health__check_firmware_health --> oqlos__tools__hardware_diagnose__health___request_firmware_json
    oqlos__tools__hardware_diagnose__health__check_firmware_identify --> oqlos__tools__hardware_diagnose__health___request_firmware_json
    oqlos__tools__hardware_diagnose__health__cmd_health --> oqlos__tools__hardware_diagnose__health__check_firmware_health
    oqlos__tools__hardware_diagnose__health__cmd_diagnose --> oqlos__tools__hardware_diagnose__discovery__list_i2c_buses
    oqlos__tools__hardware_diagnose__health__cmd_diagnose --> oqlos__tools__hardware_diagnose__health__check_firmware_identify
    oqlos__tools__hardware_diagnose__health__cmd_diagnose --> oqlos__tools__hardware_diagnose__report__format_peripheral_table
    oqlos__tools__hardware_diagnose____main_____print_list --> oqlos__tools__hardware_diagnose__discovery__list_usb_serial_devices
    oqlos__tools__hardware_diagnose____main_____print_list --> oqlos__tools__hardware_diagnose__report__format_peripheral_table
    oqlos__tools__hardware_diagnose____main_____print_list --> oqlos__tools__hardware_diagnose__discovery__list_i2c_buses
    oqlos__tools__hardware_diagnose____main_____print_health --> oqlos__tools__hardware_diagnose__health__cmd_health
    oqlos__tools__hardware_diagnose____main_____print_health --> oqlos__tools__hardware_diagnose__health__check_firmware_health
    oqlos__tools__hardware_diagnose____main_____print_calibrate --> oqlos__tools__hardware_diagnose__calibration__run_calibration_test
    oqlos__tools__hardware_diagnose____main_____print_benchmark --> oqlos__tools__hardware_diagnose__benchmark__run_benchmark
    oqlos__tools__plugin_cli___load_config_file --> oqlos__hardware__plugins__registry__PluginRegistry__load_configs_from_yaml
    oqlos__tools__plugin_cli__cmd_list --> oqlos__hardware__plugins__registry__PluginRegistry__list_plugins
    oqlos__tools__plugin_cli__cmd_status --> oqlos__hardware__plugins__registry__PluginRegistry__get_status
    oqlos__tools__plugin_cli__cmd_capabilities --> oqlos__hardware__plugins__registry__PluginRegistry__get_plugin_class
    oqlos__tools__plugin_cli__cmd_validate --> oqlos__hardware__plugins__registry__PluginRegistry__validate_all_configurations
    oqlos__tools__plugin_cli__cmd_validate --> oqlos__tools__plugin_cli___load_config_file
    oqlos__tools__plugin_cli__cmd_connect --> oqlos__hardware__plugins__registry__PluginRegistry__connect_plugin
    oqlos__tools__plugin_cli__cmd_disconnect --> oqlos__hardware__plugins__registry__PluginRegistry__disconnect_plugin
    oqlos__tools__plugin_cli__cmd_health --> oqlos__hardware__plugins__registry__PluginRegistry__health_check
    oqlos__tools__plugin_cli__cmd_health --> oqlos__hardware__plugins__registry__PluginRegistry__health_check_all
    oqlos__tools__plugin_cli__cmd_execute --> oqlos__hardware__plugins__registry__PluginRegistry__get_instance
    oqlos__tools__plugin_cli__cmd_reload --> oqlos__hardware__plugins__registry__PluginRegistry__load_configs_from_yaml
    oqlos__tools__plugin_cli__cmd_peripherals --> oqlos__hardware__plugins__registry__PluginRegistry__load_configs_from_yaml
    oqlos__tools__hardware_diagnose__shell___cmd_list --> oqlos__tools__hardware_diagnose__discovery__list_usb_serial_devices
    oqlos__tools__hardware_diagnose__shell___cmd_list --> oqlos__tools__hardware_diagnose__discovery__list_i2c_buses
    oqlos__tools__hardware_diagnose__shell___cmd_list --> oqlos__tools__hardware_diagnose__report__format_peripheral_table
    oqlos__tools__hardware_diagnose__shell___cmd_list --> oqlos__tools__hardware_diagnose__discovery__detect_chips_on_i2c
    oqlos__tools__hardware_diagnose__shell___cmd_calibrate --> oqlos__tools__hardware_diagnose__calibration__run_calibration_test
    oqlos__tools__hardware_diagnose__shell___cmd_benchmark --> oqlos__tools__hardware_diagnose__benchmark__run_benchmark
    oqlos__tools__hardware_diagnose__shell___dispatch_command --> oqlos__tools__hardware_diagnose__shell___cmd_benchmark
    oqlos__tools__hardware_diagnose__shell__interactive_shell --> oqlos__tools__hardware_diagnose__shell___dispatch_command
    oqlos__tools__hardware_diagnose__report__save_diagnostic_report --> oqlos__tools__hardware_diagnose__discovery__list_i2c_buses
    oqlos__tools__hardware_diagnose__report__save_diagnostic_report --> oqlos__tools__hardware_diagnose__health__check_firmware_health
    oqlos__tools__hardware_diagnose__report__save_diagnostic_report --> oqlos__tools__hardware_diagnose__health__check_firmware_identify
    oqlos__tools__hardware_diagnose__report__save_diagnostic_report --> oqlos__tools__hardware_diagnose__calibration__run_calibration_test
    oqlos__tools__hardware_diagnose__calibration__run_calibration_test --> oqlos__tools__hardware_diagnose__calibration___calibrate_pump
    oqlos__tools__hardware_diagnose__calibration__run_calibration_test --> oqlos__tools__hardware_diagnose__calibration___calibrate_valves
    oqlos__tools__hardware_diagnose__calibration__run_calibration_test --> oqlos__tools__hardware_diagnose__calibration___calibrate_sensors
    oqlos__tools__xml_import___utils__normalize_output_name --> oqlos__tools__xml_import___utils__is_pump_output
    oqlos__tools__xml_import___utils__normalize_output_name --> oqlos__tools__xml_import___utils__is_compressor_output
    oqlos__tools__xml_import__parser__parse_xml --> oqlos__tools__xml_import__parser___populate_report_fields
    oqlos__tools__xml_import__parser__parse_xml --> oqlos__tools__xml_import__parser___parse_intervals
    oqlos__tools__xml_import__parser__parse_xml --> oqlos__core__base__VariableStore__set
    oqlos__tools__xml_import__parser___parse_test_run --> oqlos__core__base__VariableStore__set
    oqlos__tools__xml_import__parser___parse_test_run --> oqlos__tools__xml_import__parser___parse_operation
    oqlos__tools__xml_import__parser___parse_operation_params --> oqlos__core__base__VariableStore__set
    oqlos__tools__xml_import__generators___emit_cql_output --> oqlos__tools__xml_import___utils__is_pump_output
    oqlos__tools__xml_import__generators___emit_cql_output --> oqlos__tools__xml_import___utils__is_compressor_output
    oqlos__tools__xml_import__generators___emit_cql_param --> oqlos__tools__xml_import__generators___emit_cql_sensor_param
    oqlos__tools__xml_import__generators___emit_dsl_param --> oqlos__tools__xml_import__generators___format_range
    oqlos__tools__xml_import__generators___emit_dsl_param --> oqlos__tools__xml_import__generators___mode_action
    oqlos__tools__xml_import__generators___build_steps_from_op --> oqlos__tools__xml_import__generators___append_sensor_assertion
    oqlos__tools__xml_import__generators__generate_dsl --> oqlos__tools__xml_import__generators___emit_dsl_sensors
    oqlos__tools__xml_import__generators___emit_dsl_sensors --> oqlos__core__base__VariableStore__set
    oqlos__tools__xml_import__generators___generate_cql_for_goal --> oqlos__tools__xml_import__generators___emit_cql_output
    oqlos__tools__xml_import__generators___generate_cql_for_goal --> oqlos__tools__xml_import__generators___emit_cql_param
    oqlos__tools__xml_import__generators__generate_goals_json --> oqlos__tools__xml_import__generators___build_validation_criteria
    oqlos__tools__xml_import__generators__generate_goals_json --> oqlos__tools__xml_import__generators___generate_cql_for_goal
    oqlos__tools__cql_cli__commands__run_single_command --> oqlos__tools__cql_cli__utils__build_single_command_scenario
    oqlos__tools__cql_cli__commands__run_single_command --> oqlos__tools__cql_cli__commands__run_source
    oqlos__tools__cql_cli__commands__handle_list_command --> oqlos__tools__hardware_diagnose__health__check_firmware_identify
    oqlos__tools__cql_cli__commands__handle_list_command --> oqlos__core__base__InterpreterOutput__output_yaml
    oqlos__tools__cql_cli__commands__execute_command_with_cleanup --> oqlos__core__base__InterpreterOutput__output_yaml
    oqlos__tools__cql_cli__commands__execute_command_with_cleanup --> oqlos__tools__cql_cli__commands___run_continuous_mode
    oqlos__tools__cql_cli__commands__execute_command_with_cleanup --> oqlos__tools__cql_cli__utils__build_result_payload
    oqlos__tools__cql_cli__main --> oqlos__tools__cql_cli___sync_compat_symbols
    oqlos__tools__cql_cli__utils___extract_first_action --> oqlos__core__cql_parser__parse_cql
    oqlos__tools__cql_cli__utils___extract_first_action --> oqlos__tools__cql_cli__utils__build_single_command_scenario
    oqlos__tools__cql_cli__utils___resolve_peripheral_adapter --> oqlos__tools__cql_cli__utils__normalize_target_name
    oqlos__tools__cql_cli__utils__resolve_required_adapter --> oqlos__tools__cql_cli__utils___extract_first_action
    oqlos__tools__cql_cli__utils__resolve_required_adapter --> oqlos__tools__cql_cli__utils___resolve_peripheral_adapter
    oqlos__tools__cql_cli__utils__resolve_required_adapter --> oqlos__tools__cql_cli__utils___resolve_sensor_target
    oqlos__tools__cql_cli__preflight__ensure_firmware_running --> oqlos__tools__cql_cli__preflight___is_firmware_running
    oqlos__tools__cql_cli__preflight__ensure_firmware_running --> oqlos__tools__cql_cli__preflight___start_firmware_service
    oqlos__tools__cql_cli__preflight__check_firmware_state --> oqlos__tools__hardware_diagnose__health__check_firmware_health
    oqlos__tools__cql_cli__preflight__check_firmware_state --> oqlos__tools__hardware_diagnose__health__check_firmware_identify
    oqlos__tools__cql_cli__preflight__check_firmware_state --> oqlos__tools__cql_cli__preflight___emit_preflight_error
    oqlos__tools__cql_cli__preflight__check_required_adapter --> oqlos__tools__cql_cli__utils__resolve_required_adapter
    oqlos__tools__cql_cli__preflight__check_required_adapter --> oqlos__tools__cql_cli__preflight___emit_preflight_error
    oqlos__tools__cql_cli__preflight___emit_preflight_error --> oqlos__core__base__InterpreterOutput__output_yaml
    oqlos__tools__cql_cli__preflight__emit_preflight_success --> oqlos__tools__cql_cli__preflight___emit_yaml_preflight
    oqlos__tools__cql_cli__preflight__emit_preflight_success --> oqlos__tools__cql_cli__preflight___emit_text_preflight
    oqlos__tools__cql_cli__preflight___emit_yaml_preflight --> oqlos__core__base__InterpreterOutput__output_yaml
    oqlos__tools__cql_cli__preflight__preflight_hardware --> oqlos__tools__cql_cli__preflight__check_firmware_state
    oqlos__tools__cql_cli__preflight__preflight_hardware --> oqlos__tools__cql_cli__preflight__check_required_adapter
    oqlos__tools__cql_cli__preflight__preflight_hardware --> oqlos__tools__cql_cli__preflight__emit_preflight_success
    oqlos__tools__cql_cli__preflight__preflight_hardware --> oqlos__tools__cql_cli__preflight__ensure_firmware_running
    oqlos__tools__cql_cli__main__run_file_mode --> oqlos__tools__cql_cli__utils__parse_sensor_overrides
    oqlos__tools__cql_cli__main__run_file_mode --> oqlos__tools__cql_cli__utils__validate_directory
    oqlos__tools__cql_cli__main__run_file_mode --> oqlos__tools__cql_cli__main__create_file_parser
    oqlos__tools__cql_cli__main__run_file_mode --> oqlos__tools__cql_cli__utils__build_result_payload
    oqlos__tools__cql_cli__main__run_cmd_mode --> oqlos__tools__cql_cli__utils__parse_sensor_overrides
    oqlos__tools__cql_cli__main__run_cmd_mode --> oqlos__tools__cql_cli__commands__run_single_command
    oqlos__tools__cql_cli__main__run_cmd_mode --> oqlos__tools__cql_cli__commands__execute_command_with_cleanup
    oqlos__tools__cql_cli__main__run_cmd_mode --> oqlos__tools__cql_cli__main__create_cmd_parser
    oqlos__tools__cql_cli__main__run_cmd_mode --> oqlos__tools__cql_cli__preflight__preflight_hardware
    oqlos__tools__cql_cli__main__main --> oqlos__tools__cql_cli__main__run_file_mode
    oqlos__tools__cql_cli__main__main --> oqlos__tools__cql_cli__main__run_cmd_mode
    oqlos__tools__cql_cli__main__main --> oqlos__tools__cql_cli__commands__handle_list_command
    oqlos__tools__cql_cli__main__main --> oqlos__tools__cql_cli__main__create_file_parser
    oqlos__tools__hardware_diagnose__discovery__list_usb_serial_devices --> oqlos__tools__hardware_diagnose__discovery___run_shell_command
    oqlos__tools__hardware_diagnose__discovery__list_i2c_buses --> oqlos__tools__hardware_diagnose__discovery___run_shell_command
    oqlos__tools__hardware_diagnose__discovery__detect_chips_on_i2c --> oqlos__tools__hardware_diagnose__discovery___run_shell_command
    oqlos__hardware__config_schema__get_hardware_config --> oqlos__hardware__plugins__registry__PluginRegistry__load_configs_from_yaml
    oqlos__hardware__config_schema__load_config_from_yaml --> oqlos__hardware__plugins__registry__PluginRegistry__load_configs_from_yaml
    oqlos__hardware__gateway___ModbusAdapter____init__ --> oqlos__hardware__discovery__probe_waveshare_modbus
    oqlos__hardware__plugin_gateway__PluginHardwareGateway____init__ --> oqlos__config__get_settings
    oqlos__hardware__plugin_gateway__PluginHardwareGateway___load_hardware_schema --> oqlos__hardware__plugins__registry__PluginRegistry__load_configs_from_yaml
    oqlos__hardware__plugin_gateway__PluginHardwareGateway___load_plugin_configs --> oqlos__hardware__plugins__registry__PluginRegistry__load_configs_from_yaml
    oqlos__hardware__plugin_gateway__PluginHardwareGateway___create_default_configs --> oqlos__config__get_settings
    oqlos__hardware__plugin_gateway__PluginHardwareGateway___initialize_plugins --> oqlos__hardware__plugins__registry__PluginRegistry__create_instance
    oqlos__hardware__plugin_gateway__PluginHardwareGateway__reload_configs --> oqlos__hardware__plugins__registry__PluginRegistry__load_configs_from_yaml
    oqlos__hardware__plugin_gateway__PluginHardwareGateway__health --> oqlos__hardware__plugins__registry__PluginRegistry__health_check_all
    oqlos__hardware__discovery___unique_preserving_order --> oqlos__core__base__VariableStore__set
    oqlos__hardware__discovery___build_probe_candidates --> oqlos__hardware__discovery___unique_preserving_order
    oqlos__hardware__discovery__probe_waveshare_modbus --> oqlos__hardware__discovery__list_serial_ports
    oqlos__hardware__discovery__probe_waveshare_modbus --> oqlos__hardware__discovery___build_probe_candidates
    oqlos__hardware__discovery__probe_waveshare_modbus --> oqlos__hardware__discovery___make_probe_failure_result
    oqlos__hardware__discovery__probe_waveshare_modbus --> oqlos__hardware__discovery___make_pymodbus_fallback_result
    oqlos__hardware__discovery__probe_waveshare_modbus --> oqlos__hardware__discovery___try_modbus_connection
    oqlos__hardware__discovery__probe_waveshare_modbus --> oqlos__hardware__discovery___make_probe_success_result
    oqlos__hardware__firmware_adapter__FirmwareAdapter____init__ --> oqlos__config__get_settings
    oqlos__hardware__firmware_adapter__FirmwareAdapter___get_lung_motor_url --> oqlos__config__get_settings
    oqlos__hardware__firmware_adapter__FirmwareAdapter__set_peripheral --> oqlos__hardware__firmware_adapter___parse_numeric
    oqlos__hardware__firmware_adapter__FirmwareAdapter___handle_lung_action --> oqlos__hardware__firmware_adapter___parse_numeric
    oqlos__hardware__firmware_adapter__FirmwareAdapter___handle_pump_action --> oqlos__hardware__firmware_adapter___parse_numeric
    oqlos__hardware__plugins__registry__PluginRegistry__discover_entry_point_plugins --> oqlos__hardware__plugins__base__get_pluggy_manager
    oqlos__hardware__plugins__lung__LungPlugin__disconnect --> oqlos__hardware__plugins___shared__http_disconnect
    oqlos__hardware__plugins__lung__LungPlugin__health_check --> oqlos__hardware__plugins___shared__not_connected_health
    oqlos__hardware__plugins__lung__LungPlugin__health_check --> oqlos__hardware__plugins___shared__health_check_exception
    oqlos__hardware__plugins__lung__LungPlugin__health_check --> oqlos__hardware__plugins___shared__http_health_check
    oqlos__hardware__plugins__motor__MotorPlugin__disconnect --> oqlos__hardware__plugins___shared__http_disconnect
    oqlos__hardware__plugins__motor__MotorPlugin__health_check --> oqlos__hardware__plugins___shared__not_connected_health
    oqlos__hardware__plugins__motor__MotorPlugin__health_check --> oqlos__hardware__plugins___shared__health_check_exception
    oqlos__hardware__plugins__motor__MotorPlugin__health_check --> oqlos__hardware__plugins___shared__http_health_check
    oqlos__hardware__plugins__piadc__PiadcPlugin__disconnect --> oqlos__hardware__plugins___shared__http_disconnect
    oqlos__hardware__plugins__piadc__PiadcPlugin__health_check --> oqlos__hardware__plugins___shared__not_connected_health
    oqlos__hardware__plugins__piadc__PiadcPlugin__health_check --> oqlos__hardware__plugins___shared__http_health_check
    oqlos__hardware__plugins__piadc__PiadcPlugin__health_check --> oqlos__hardware__plugins___shared__health_check_exception
    oqlos__shared__release_version___read_version_from_package_json --> oqlos__shared__release_version__clean_version
    oqlos__shared__release_version___read_version_from_text --> oqlos__shared__release_version__clean_version
    oqlos__shared__release_version__resolve_release_version --> oqlos__shared__release_version___version_candidates
    oqlos__shared__release_version__resolve_release_version --> oqlos__shared__release_version__clean_version
    oqlos__shared__release_version__resolve_release_version --> oqlos__shared__release_version___run_git
    oqlos__shared__release_version__resolve_release_version --> oqlos__shared__release_version___read_version_from_package_json
    oqlos__shared__release_version__resolve_release_version --> oqlos__shared__release_version___read_version_from_text
    oqlos__shared__release_version__main --> oqlos__shared__release_version__resolve_release_version
    oqlos__shared__file_ops__read_file --> oqlos__shared__file_ops___ensure_safe_path
    oqlos__shared__file_ops__write_file --> oqlos__shared__file_ops___ensure_safe_path
    oqlos__shared__config_factory__create_nfo_setup --> oqlos__shared__release_version__resolve_release_version
    oqlos__shared__event_server__ConnectionManager____init__ --> oqlos__core__base__VariableStore__set
    oqlos__shared__version_endpoint__create_version_router --> oqlos__shared__version_endpoint__build_version_payload
    oqlos__api__plugins__list_plugins --> oqlos__hardware__plugins__registry__PluginRegistry__list_plugins
    oqlos__api__plugins__get_plugin_status --> oqlos__hardware__plugins__registry__PluginRegistry__get_status
    oqlos__api__plugins__get_plugin_info --> oqlos__hardware__plugins__registry__PluginRegistry__get_plugin_class
    oqlos__api__plugins__get_plugin_health --> oqlos__hardware__plugins__registry__PluginRegistry__health_check
    oqlos__api__plugins__connect_plugin --> oqlos__hardware__plugins__registry__PluginRegistry__connect_plugin
    oqlos__api__plugins__disconnect_plugin --> oqlos__hardware__plugins__registry__PluginRegistry__disconnect_plugin
    oqlos__api__plugins__execute_plugin_command --> oqlos__hardware__plugins__registry__PluginRegistry__get_instance
    oqlos__api__plugins__validate_plugin_configs --> oqlos__hardware__plugins__registry__PluginRegistry__validate_all_configurations
    oqlos__api__state__get_state --> oqlos__api__state___compose_named_state
    oqlos__api__state__stream_values --> oqlos__api__state___generate_sinusoidal_values
    oqlos__api__state__get_sim_state --> oqlos__api__state___compose_named_state
    oqlos__api__state__get_sim_state --> oqlos__api__state___compose_sim_state_list
    oqlos__api__state__get_variables_alias --> oqlos__api__state__fetch_variables
    oqlos__api__state___maybe_register_dsl_from_content --> oqlos__api__state___extract_inline_dsl
    oqlos__api__state___maybe_register_dsl_from_content --> oqlos__core__parser__parse_dsl_to_goal_with_issues
    oqlos__api__state___handle_start --> oqlos__api__state___extract_scenario_id
    oqlos__api__state___handle_start --> oqlos__api__state___extract_inline_dsl
    oqlos__api__state___handle_start --> oqlos__api__state___maybe_register_dsl_from_content
    oqlos__api__scenarios__get_scenario --> oqlos__api__scenarios__fetch_scenarios
    oqlos__api__scenarios___extract_display_fields --> oqlos__api__scenarios___compute_slug
    oqlos__api__scenarios___extract_goals --> oqlos__api__scenarios___parse_content_to_goals
    oqlos__api__scenarios___normalize_scenario_row --> oqlos__api__scenarios___extract_id
    oqlos__api__scenarios___normalize_scenario_row --> oqlos__api__scenarios___extract_display_fields
    oqlos__api__scenarios___normalize_scenario_row --> oqlos__api__scenarios___extract_goals
    oqlos__api__scenarios__fetch_scenarios --> oqlos__api__scenarios___fetch_raw_from_sources
    oqlos__api__scenarios__fetch_scenarios --> oqlos__api__scenarios___normalize_scenario_row
    oqlos__api__scenarios___collect_dsl_strings --> oqlos__api__scenarios___ensure_list
    oqlos__api__scenarios___register_single_dsl_scenario --> oqlos__api__scenarios___collect_dsl_strings
    oqlos__api__scenarios___register_single_dsl_scenario --> oqlos__api__scenarios___parse_goals_from_dsl
    oqlos__api__scenarios___register_single_dsl_scenario --> oqlos__api__scenarios___merge_goals_into_scenario
    oqlos__api__scenarios__register_dsl --> oqlos__api__scenarios___normalize_dsl_payload
    oqlos__api__scenarios__register_dsl --> oqlos__api__scenarios___register_single_dsl_scenario
    oqlos__api__execution___current_projection --> oqlos__api__execution___build_step_labels
    oqlos__api__execution___current_projection --> oqlos__api__execution___resolve_current_index
    oqlos__api__execution__start_execution --> oqlos__api__execution___register_dsl_scenario
    oqlos__api__execution___register_dsl_scenario --> oqlos__core__parser__parse_dsl_to_goal_with_issues
    oqlos__api__execution__get_execution_projection --> oqlos__api__execution___current_projection
    oqlos__api__execution__execution_stream --> oqlos__api__execution___current_projection
    oqlos__api__execution__execution_logs_stream --> oqlos__api__execution___resolve_step_label
    oqlos__api__logs___get_service --> oqlos__shared__logs_query__resolve_logs_db_path
    oqlos__api__logs__get_logs --> oqlos__api__logs___get_service
    oqlos__api__logs__get_log_stats --> oqlos__api__logs___get_service
    oqlos__api__hardware___probe_modbus_rtu --> oqlos__hardware__discovery__probe_waveshare_modbus
    oqlos__api__hardware___probe_all_hardware --> oqlos__api__hardware___scan_usb_devices
    oqlos__api__hardware___probe_all_hardware --> oqlos__api__hardware___probe_tic249
    oqlos__api__hardware___probe_all_hardware --> oqlos__api__hardware___probe_dri0050
    oqlos__api__hardware___probe_all_hardware --> oqlos__api__hardware___probe_i2c_ads1115
    oqlos__api__hardware___probe_all_hardware --> oqlos__api__hardware___probe_modbus_rtu
    oqlos__api__hardware___collect_hardware_diagnostics --> oqlos__api__hardware___scan_usb_devices
    oqlos__api__hardware___collect_hardware_diagnostics --> oqlos__hardware__discovery__list_serial_ports
    oqlos__api__hardware__hardware_health --> oqlos__api__hardware___gw
    oqlos__api__hardware__set_valve --> oqlos__api__hardware___gw
    oqlos__api__hardware__set_pump --> oqlos__api__hardware___gw
    oqlos__api__hardware__read_sensor --> oqlos__api__hardware___gw
    oqlos__api__hardware__set_lung --> oqlos__api__hardware___gw
    oqlos__api__hardware__stop_lung --> oqlos__api__hardware___gw
    oqlos__api__main__index_page --> oqlos__shared___endpoint_helpers__serve_html_page
    oqlos__api__main__editor_page --> oqlos__shared___endpoint_helpers__serve_html_page
    oqlos__api__editor___safe_path --> oqlos__shared__file_ops___ensure_safe_path
    oqlos__api__editor__list_files --> oqlos__shared__file_ops__iter_entries
    oqlos__api__editor__read_file_endpoint --> oqlos__shared__file_ops__read_file
    oqlos__api__editor__write_file_endpoint --> oqlos__shared__file_ops__write_file
    oqlos__api__editor__execute_scenario --> oqlos__api__editor___safe_path
    oqlos__dsl__schema___normalize_name_list --> oqlos__core__base__VariableStore__set
    oqlos__dsl__schema___build_inferred_object_function_map --> oqlos__dsl__schema___normalize_name_list
    oqlos__dsl__schema___build_inferred_param_unit_map --> oqlos__dsl__schema___normalize_name_list
    oqlos__dsl__schema___merge_object_function_map --> oqlos__dsl__schema___normalize_name_list
    oqlos__dsl__schema___merge_param_unit_map --> oqlos__dsl__schema___normalize_name_list
    oqlos__dsl__schema__get_default_dsl_schema --> oqlos__dsl__schema___build_inferred_object_function_map
    oqlos__dsl__schema__get_default_dsl_schema --> oqlos__dsl__schema___build_inferred_param_unit_map
