flowchart TD
%% generated in 0.04s

    %% Entry points (blue)
    classDef entry fill:#4dabf7,stroke:#1971c2,color:#fff

    subgraph Core
        setup_hardware_and_run_oql__main["main"]
        frontend__src__main__LocalizedApp["LocalizedApp"]
        frontend__src__hooks__useWsStatus__useWsStatus["useWsStatus"]
        frontend__src__hooks__useWsStatus__client["client"]
        frontend__src__hooks__useWsStatus__onOpen["onOpen"]
        frontend__src__hooks__useWsStatus__onClose["onClose"]
        frontend__src__hooks__useMapEditorSidebarAutoCollapse__useMapEditorSidebarAutoCollapse["useMapEditorSidebarAutoCollaps"]
        frontend__src__hooks__useMapEditorSidebarAutoCollapse__root["root"]
        frontend__src__hooks__useMapEditorSidebarAutoCollapse__font["font"]
        frontend__src__hooks__useMapEditorSidebarAutoCollapse__viewportWidth["viewportWidth"]
        frontend__src__hooks__useMapEditorSidebarAutoCollapse__denseFont["denseFont"]
        frontend__src__hooks__useMapEditorSidebarAutoCollapse__minWidth["minWidth"]
        frontend__src__hooks__useMapEditorSidebarAutoCollapse__observer["observer"]
        frontend__src__hooks__useMapEditorHardwareEvents__useMapEditorHardwareEvents["useMapEditorHardwareEvents"]
        frontend__src__hooks__useMapEditorHardwareEvents__wsUrl["wsUrl"]
        ...["+1460 more"]
    end

    subgraph Exporters
        frontend__src__pages__HardwareRestart__exportText["exportText"]
        oqlos__api__hardware_mapping_store__MappingStore__export_text["export_text"]
        oqlos__api___hw3_mapping__hardware_mapping_export_v3["hardware_mapping_export_v3"]
    end

    class setup_hardware_and_run_oql__main,frontend__src__main__LocalizedApp,frontend__src__hooks__useWsStatus__useWsStatus,frontend__src__hooks__useWsStatus__client,frontend__src__hooks__useWsStatus__onOpen,frontend__src__hooks__useWsStatus__onClose,frontend__src__hooks__useMapEditorSidebarAutoCollapse__useMapEditorSidebarAutoCollapse,frontend__src__hooks__useMapEditorSidebarAutoCollapse__root,frontend__src__hooks__useMapEditorSidebarAutoCollapse__font,frontend__src__hooks__useMapEditorSidebarAutoCollapse__viewportWidth entry
