"""Sample test — auto-generated by goal."""

def test_placeholder():
    """Placeholder test to verify the test setup works."""
    assert True

def test_import():
    """Verify the main module can be imported."""
    import oqlos.api.main  # noqa: F401
